spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: mahesh
    url: jdbc:mysql://localhost:3306/quiz_app
    #        url: jdbc:mysql://192.168.2.47:3306/test
    username: mahesh

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
