server:
  port: 1434

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**


okta:
  oauth2:
    issuer: https://dev-50586774.okta.com/oauth2/default
    audience: api://default
    client-id: 0oa9oq0rgxTTCumiX5d7
    client-secret: 0es8puJzcIiOIB0iuiOEjUUoCh8_5AWmyXwDCIbU
    scopes: openid, profile, email, offline_access


