spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbatch
    username: mahesh
    password: mahesh
  jpa:
    properties:
      hibernate:
      format-sql: true
    hibernate:
      ddl-auto: none
    show-sql: true

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: ALWAYS